apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: acme-greeting-api-restful-k8s
  name: acme-greeting-api-restful-k8s
spec:
  containers:
  - image: acme/acme-greeting-api-restful-k8s:latest
    name: acme-greeting-api-restful-k8s
    imagePullPolicy: Never  
    resources: {}
    command: [ "echo", "SUCCESS" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
